- disclosureID: ISTIO-SECURITY-2022-004
  description: Unauthenticated control plane denial of service attack due to stack
    exhaustion
  impactScore: 7.5
  affectedReleases:
  - rangetype: range
    end:
      major: "1.11"
      minor: "0"
  - rangetype: range
    start:
      major: "1.11"
      minor: "0"
    end:
      major: "1.11"
      minor: "7"
  - rangetype: range
    start:
      major: "1.12"
      minor: "0"
    end:
      major: "1.12"
      minor: "4"
  - rangetype: range
    start:
      major: "1.13"
      minor: "0"
    end:
      major: "1.13"
      minor: "1"
- disclosureID: ISTIO-SECURITY-2022-003
  description: Multiple CVEs related to istiod Denial of Service and Envoy.
  impactScore: 7.5
  affectedReleases:
  - rangetype: range
    end:
      major: "1.11"
      minor: "0"
  - rangetype: range
    start:
      major: "1.11"
      minor: "0"
    end:
      major: "1.11"
      minor: "6"
  - rangetype: range
    start:
      major: "1.12"
      end: "0"
    end:
      major: "1.12"
      minor: "3"
  - rangetype: particular
    particular:
      major: "1.13"
      minor: "0"
- disclosureID: ISTIO-SECURITY-2022-001
  description: Authorization Policy For Host Rules During Upgrades.
  impactScore: 6.8
  affectedReleases:
  - rangetype: range
    start:
      major: "1.12"
      end: "0"
    end:
      major: "1.12"
      minor: "1"
- disclosureID: ISTIO-SECURITY-2022-002
  description: Privileged Escalation in Kubernetes Gateway API
  impactScore: 4.7
  affectedReleases:
  - rangetype: range
    start:
      major: "1.12"
      end: "0"
    end:
      major: "1.12"
      minor: "1"
- disclosureID: ISTIO-SECURITY-2021-008
  description: Multiple CVEs related to AuthorizationPolicy, EnvoyFilter and Envoy
  impactScore: 8.6
  affectedReleases:
  # All releases prior to 1.9.8
  - rangetype: range
    end:
      major: "1.9"
      minor: "7"
  - rangetype: range
    start:
      major: "1.10"
      end: "0"
    end:
      major: "1.10"
      minor: "3"
  - rangetype: particular
    particular:
      major: "1.11"
      minor: "0"
- disclosureID: ISTIO-SECURITY-2021-007
  description: Istio contains a remotely exploitable vulnerability where credentials
    specified in the Gateway and DestinationRule credentialName field can be accessed
    from different namespaces
  impactScore: 9.1
  affectedReleases:
  # All 1.8 patch releases
  - rangetype: range
    end:
      major: "1.9"
      minor: "0"
  - rangetype: range
    start:
      major: "1.9"
      end: "0"
    end:
      major: "1.9"
      minor: "5"
  - rangetype: range
    start:
      major: "1.10"
      end: "0"
    end:
      major: "1.10"
      minor: "1"
- disclosureID: ISTIO-SECURITY-2021-006
  description: An external client can access unexpected services in the cluster, bypassing
    authorization checks, when a gateway is configured with AUTO_PASSTHROUGH routing
    configuration
  impactScore: 10
  affectedReleases:
  - rangetype: range
    end:
      major: "1.8"
      minor: "5"
  - rangetype: range
    start:
      major: "1.9"
      end: "0"
    end:
      major: "1.9"
      minor: "4"
- disclosureID: ISTIO-SECURITY-2021-005
  description: HTTP request paths with multiple slashes or escaped slash characters may bypass path based authorization rules.
  impactScore: 8.1
  affectedReleases:
  - rangetype: range
    end:
      major: "1.8"
      minor: "5"
  - rangetype: range
    start:
      major: "1.9"
      end: "0"
    end:
      major: "1.9"
      minor: "4"
- disclosureID: ISTIO-SECURITY-2021-004 # special case, no end release, no CVE fix.
  description: Potential misuse of mTLS-only fields in AuthorizationPolicy with plain
    text traffic
  affectedReleases:
  - rangetype: range
    start:
      major: "1.5"
      minor: "0"
- disclosureID: ISTIO-SECURITY-2021-003
  impactScore: 7.5
  affectedReleases:
  - rangetype: range
    end:
      major: "1.8"
      minor: "4"
  - rangetype: range
    start:
      major: "1.9"
      minor: "0"
    start:
      major: "1.9"
      minor: "2"
- disclosureID: ISTIO-SECURITY-2021-002
  description: Upgrades from older Istio versions can affect access control to an
    ingress gateway due to a change of container ports
  affectedReleases:
  - rangetype: range
    start:
      major: "1.6"
      minor: "0"
- disclosureID: ISTIO-SECURITY-2021-001
  description: JWT authentication can be bypassed when AuthorizationPolicy is misused
  affectedReleases:
  - rangetype: range
    start:
      major: "1.9"
      minor: "0"
    end:
      major: "1.9"
      minor: "0"
  impactScore: 8.2
- disclosureID: ISTIO-SECURITY-2020-011
  description: Envoy incorrectly restores the proxy protocol downstream address for
    non-HTTP connections
  affectedReleases:
  - rangetype: range
    start:
      major: "1.8"
      minor: "0"
- disclosureID: ISTIO-SECURITY-2020-010
  impactScore: 8.3
  affectedReleases:
  - rangetype: range
    start:
      major: "1.6"
      minor: "0"
    end:
      major: "1.6"
      minor: "10"
  - rangetype: range
    start:
      major: "1.7"
      minor: "0"
    end:
      major: "1.7"
      minor: "2"
- disclosureID: ISTIO-SECURITY-2020-009
  description: Incorrect Envoy configuration for wildcard suffixes used for Principals/Namespaces
    in Authorization Policies for TCP Services
  impactScore: 6.8
  affectedReleases:
  - rangetype: range
    start:
      major: "1.5"
      minor: "0"
    end:
      major: "1.5"
      minor: "8"
  - rangetype: range
    start:
      major: "1.6"
      minor: "0"
    end:
      major: "1.6"
      minor: "7"
- disclosureID: ISTIO-SECURITY-2020-008
  description: Incorrect validation of wildcard DNS Subject Alternative Names
  impactScore: 6.6
  affectedReleases:
  - rangetype: range
    start:
      major: "1.5"
      minor: "0"
    end:
      major: "1.5"
      minor: "7"
  - rangetype: range
    start:
      major: "1.6"
      minor: "0"
    end:
      major: "1.6"
      minor: "3"
  - rangetype: range
    end:
      major: "1.5" # TODO: testing.
- disclosureID: ISTIO-SECURITY-2020-007
  description: Multiple denial of service vulnerabilities in Envoy
  impactScore: 7.5
  affectedReleases:
  - rangetype: range
    start:
      major: "1.5"
      minor: "0"
    end:
      major: "1.5"
      minor: "6"
  - rangetype: range
    start:
      major: "1.6"
      minor: "0"
    end:
      major: "1.6"
      minor: "3"
- disclosureID: ISTIO-SECURITY-2020-006
  description: Denial of service in the HTTP2 library used by Envoy
  impactScore: 7.5
  affectedReleases:
  - rangetype: range
    start:
      major: "1.4"
      minor: "0"
    end:
      major: "1.4"
      minor: "9"
  - rangetype: range
    start:
      major: "1.5"
      minor: "0"
    end:
      major: "1.4"
      minor: "4"
  - rangetype: range
    start:
      major: "1.6"
      minor: "0"
    end:
      major: "1.6"
      minor: "1"
# - disclosureID: ISTIO-SECURITY-2020-005
#   description: Denial of service affecting telemetry v2
#   impactScore: 7.5
# - disclosureID: ISTIO-SECURITY-2020-004
#   description: Default Kiali security configuration allows full control of mesh
#   impactScore: 8.7
# - disclosureID: ISTIO-SECURITY-2020-003
#   description: Two uncontrolled resource consumption and two incorrect access control
#     vulnerabilities in Envoy
#   impactScore: 7.5
# - disclosureID: ISTIO-SECURITY-2020-001
#   description: Authentication Policy bypass
#   impactScore: 9
# - disclosureID: ISTIO-SECURITY-2020-002
#   description: Mixer policy check bypass caused by improperly accepting certain request
#     headers
#   impactScore: 7.4
# - disclosureID: ISTIO-SECURITY-2019-007
#   description: Heap overflow and improper input validation in Envoy
#   impactScore: 9
# - disclosureID: ISTIO-SECURITY-2019-006
#   description: Denial of service
#   impactScore: 7.5
# - disclosureID: ISTIO-SECURITY-2019-005
#   description: Denial of service caused by the presence of numerous HTTP headers in
#     client requests
#   impactScore: 7.5
# - disclosureID: Istio 1.2.4 sidecar image vulnerability
#   description: An erroneous 1.2.4 sidecar image was available due to a faulty release
#     operation
# - disclosureID: ISTIO-SECURITY-2019-004
#   description: Multiple denial of service vulnerabilities related to HTTP2 support
#     in Envoy
#   impactScore: 7.5
# - disclosureID: ISTIO-SECURITY-2019-003
#   description: Denial of service in regular expression parsing
#   impactScore: 7.5
# - disclosureID: ISTIO-SECURITY-2019-002
#   description: Denial of service affecting JWT access token parsing
#   impactScore: 7.5
# - disclosureID: ISTIO-SECURITY-2019-001
#   description: Incorrect access control
#   impactScore: 8.9
