- disclosureID: ISTIO-SECURITY-2022-004
  description: Unauthenticated control plane denial of service attack due to stack
    exhaustion
  impactScore: 7.5
  affectedReleases:
  - rangetype: range
    end:
      major: "1.11"
      minor: "0"
  - rangetype: range
    start:
      major: "1.11"
      minor: "0"
    end:
      major: "1.11"
      minor: "7"
  - rangetype: range
    start:
      major: "1.12"
      minor: "0"
    end:
      major: "1.12"
      minor: "4"
  - rangetype: range
    start:
      major: "1.13"
      minor: "0"
    end:
      major: "1.13"
      minor: "1"